### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by YanShuang17** [mjq11302010044/RRPN_plusplus#1]
Hello, thanks for your paper and codes. Can you upload some pretrain models?

**Comment by mjq11302010044** [comment]
Thanks for your advice, we will provide the links in google drive:

*ICDAR 2015 F-measure 89.0* :
https://drive.google.com/file/d/1nv-ZjbYBj8ePZRa_fAhbHvzm7HqSxPWK/view?usp=sharing
*SynthText pretrained*:
https://drive.google.com/file/d/1RuqEg8pkN_l-4_KhOHzOeZcFiihQlxUT/view?usp=sharing

Enjoy it !

Yanshuang <notifications@github.com> 于2020年10月20日周二 下午4:31写道：

**Comment by YanShuang17** [comment]
Thanks very much, best wishes!
