### ISSUE TITLE
question about the angle

### ISSUE THREAD

**Issue by WhiteCipher** [mjq11302010044/RRPN_plusplus#11]
I'm puzzled when read the code, it looks that the angle regression range should be [-45，45] according to https://github.com/mjq11302010044/RRPN_plusplus/blob/3552feb0b3adf5601399a05140b52ce2961f0693/maskrcnn_benchmark/structures/rboxlist_ops.py#L82, but in dataset code "rotation_series.py", its not limited to this range ?

**Comment by mjq11302010044** [comment]
@WhiteCipher See **SpottingDataset** in rrpn_e2e_series.py, you will get what you want to know.

**Comment by WhiteCipher** [comment]
Oh, i got it in RandomRotationIn90. Its not easy to find it exists in a transform func.  At last, thank you for the good work.

**Comment by mjq11302010044** [comment]
@WhiteCipher Thanks for your focus on the project. :)
