### ISSUE TITLE
ROTATION_RANGE 

### ISSUE THREAD

**Issue by asif-salim** [mjq11302010044/RRPN_plusplus#14]
How to set this parameter for a custom dataset?

**Comment by mjq11302010044** [comment]
@asif-salim You can configure the dataset following the instruction in the ReadMe.

**Comment by asif-salim** [comment]
@mjq11302010044  Thanks. But this parameter is passed as an input inside configs/arpn/e2e_rrpn_R_50_C4_1x_train_AFPN_RT_LERB.yaml. The default is set as (20,10). Can you describe what this parameter is?

**Comment by mjq11302010044** [comment]
@asif-salim Hi, the parameter you mentioned of is to bound the rotation augmentation, the first 20 means the interval range R, while the second 10 means the larger bound of the range, and forming the interval of the rotation range in [S-R, S].

**Comment by asif-salim** [comment]
@mjq11302010044 Thanks
