### ISSUE TITLE
ModuleNotFoundError: No module named 'maskrcnn_benchmark.data.datasets.coco_text'

### ISSUE THREAD

**Issue by Shualite** [mjq11302010044/RRPN_plusplus#2]
I found coco_text file is empty, when i try to train it by end-to-end.

rrpn_e2e_series.py line 20.

**Comment by mjq11302010044** [comment]
@Shualite Thanks for your report, we are working on it. But you can also clone it from the original repo of coco-text https://github.com/andreasveit/coco-text, and to put it in the correct folder.

**Comment by Shualite** [comment]
thx.
