### ISSUE TITLE
Help with testing using own images

### ISSUE THREAD

**Issue by ShaheenPerveen** [mjq11302010044/RRPN_plusplus#5]
Hi

The section titled **"Testing"** provides some information on testing the implementation.
I have tried to understand the mentioned step but I am confused and unable to navigate the steps to test the model on my own images.
What I was looking for is to use the pre-trained models[pre-trained on any dataset] on my own images. Let's say that I have a directory with images: /user/sp/test_images which I would like to test, what all modifications do I need to make in files from this repository. I don't see any step which mentions where to include own test data's directory path
For example the step: "Choose the dataset you want to evaluate on. 
TEST:
  DATASET_NAME: "IC15" # Choice can be "IC15", "LSVT" and so on
  MODE: "DET" # DET for detection evaluation or E2E for recognition results in the spotter"
doesn't exactly tell you anything about your own test directory path, this only helps you to choose from fixed dataset. 
I am unable to grasp what fields to change in: $RRPN_ROOT/configs/arpn_E2E/e2e_rrpn_R_50_C4_1x_test_AFPN_RT_LERB_Spotter.yaml
If anyone else has been able to test this implementation on their own data, please help with the requisite steps.
Also, couldn't find the file "$RRPN_ROOT/demo/rrpn_e2e_series.py".
Any help would be appreciated

**Comment by mjq11302010044** [comment]
Hi,
Thanks for your report. Currently, you can modify the code in
rrpn_e2e_infer.py to test your own image. For example, you can extend the
DATASET dictionary to support your image folder, and group your own image
into the folder.

"$RRPN_ROOT/demo/rrpn_e2e_series.py"  here should be
"$RRPN_ROOT/demo/rrpn_e2e_infer.py" . Thanks for pointing out the mistake
and I will correct it in the repo.

Thanks,
Jianqi

Shaheen Perveen <notifications@github.com> 于2020年11月25日周三 下午4:28写道：

**Comment by ShaheenPerveen** [comment]
Hi @mjq11302010044 

Thank you for your response.
Are you referring to "testing_dataset" variable defined in rrpn_e2e_infer.py file or are you referring to "TEST:
  DATASET_NAME: "COCO-TEXT"
  CASCADE: False
  MODE: "DET" # DET or E2E
DATALOADER:
  SIZE_DIVISIBILITY: 1" 
from the file $RRPN_ROOT/configs/arpn_E2E/e2e_rrpn_R_50_C4_1x_test_AFPN_RT_LERB_Spotter.yaml.

In the config file: $RRPN_ROOT/configs/arpn_E2E/e2e_rrpn_R_50_C4_1x_test_AFPN_RT_LERB_Spotter.yaml, I have noticed that the "COCO-TEXT" defined under DATASET_NAME: "COCO-TEXT" is also present in rrpn_e2e_infer.py defined as part of "testing_dataset" variable where it has been mentioned as:
'COCO-TEXT':{
            'testing_image_dir':
                '../hard_space1/mjq/coco_text/train2014/',
            'off': [0, 40000],}

Do you suggest that I create another variable in "testing_dataset" with my dataset name say "EVAL-RRPN" with the directory path and change the DATASET_NAME: "COCO-TEXT" in e2e_rrpn_R_50_C4_1x_test_AFPN_RT_LERB_Spotter.yaml to "EVAL-RRPN" to run the demo on my folder? Or I have understood incorrectly? Please clarify.
Another doubt, what does 'off': [0, 40000] mean, what will be the value of this variable for my dataset? 
Also, do I need to change anything else apart from these two to run my demo?

**Comment by mjq11302010044** [comment]
@ShaheenPerveen Of course you can reimplement with your own settings :)

**Comment by ShaheenPerveen** [comment]
@mjq11302010044 Thanks.
Just to clarify, when you said "you can extend the
DATASET dictionary to support your image folder, and group your own image
into the folder", you meant "testing_dataset" variable defined in rrpn_e2e_infer.py file?
Or somethign else?
Could you also please help in understanding 'off': [0, 40000]" defined in testing_dataset?

**Comment by mjq11302010044** [comment]
@ShaheenPerveen Yes, the "testing_dataset" is the exact variable name. The 'off' key is not necessarily the number of the image, you can assign a number larger than the size of our dataset here. For details you can refer to the code that processing the dictionary.
