### ISSUE TITLE
Run testing on machine without GPU

### ISSUE THREAD

**Issue by ShaheenPerveen** [mjq11302010044/RRPN_plusplus#7]
Hi

I was following the instructions in INSTALL.md and I am encountering an error at the line:
```
python rotation_setup.py install
```
The error is:
```
Traceback (most recent call last):
  File "rotation_setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "rotation_setup.py", line 46, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
```
This is expected as I am trying ti setup on a machine without GPU. Could you please suggest how do I solve this? i.e. basically set up on a machine without GPU and run the testing on CPU?

**Comment by mjq11302010044** [comment]
@ShaheenPerveen Sorry, currently we haven't supported testing in CPU yet, you may refer to the code in detectron2 for re-implementation.
